#Drone CI File!
#Commit Message: Drone! Captain Canary is here!!!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
  - maven:
      goals: clean install
      pom-file: "/home/haripreethi/java-poc-master/pom.xml"
after:
  - artifacts:
      include: "/home/haripreethi/java-poc-master/target/*"


  
    

#- name: publish  
  #image: plugins/docker
  #settings:
    #username:
      #from_secret: docker_username
    #password:
     # from_secret: docker_password
   # repo: haripreethisagar/drone3
    #auto_tag: true
    #auto_tag_suffix: drone-build
