#Drone CI File!
#Commit Message: Drone! Captain Canary is here!!!
kind: pipeline
type: ssh
name: default
server:
  host: 65.52.34.188
  user: haripreethi
  password:
    from_secret: ssh_password
steps:
  build:
     name: pom.xml
     commands: 
        -mvn -f /home/haripreethi/java-poc-master
        -mvn package -DskipTests=true
  test:
     name: pom.xml
     commands: mvn test



  
    

#- name: publish  
  #image: plugins/docker
  #settings:
    #username:
      #from_secret: docker_username
    #password:
     # from_secret: docker_password
   # repo: haripreethisagar/drone3
    #auto_tag: true
    #auto_tag_suffix: drone-build
