#Drone CI File!
#Commit Message: Drone! Captain Canary is here!!

kind: pipeline
type: ssh
name: default
steps:
- name: java-poc
  image: appleboy/drone-ssh
  settings:
    host: 65.52.34.188
    user: haripreethi
    password:
       from_secret: ssh_password
- name: build
  mavenPomFile: 'pom.xml'
  #image: golang:1.13
  commands:
    - mvn -f /home/haripreethi/java-poc-master
    - mvn compile
    - mvn package
    - ls -R

#- name: publish  
  #image: plugins/docker
  #settings:
    #username:
      #from_secret: docker_username
    #password:
     # from_secret: docker_password
   # repo: haripreethisagar/drone3
    #auto_tag: true
    #auto_tag_suffix: drone-build
